name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Poetry
        uses: poetry/actions/setup-poetry@v2
        with:
          poetry-version: "1.x"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run pytest
